server:
  port: 80

spring:
  web:
    resources:
      static-locations: classpath:/webapp/dist/
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid:
        initial-size: 3
        max-active: 100
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        filters: stat,wall
        share-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 100
      datasource:
        cms:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://cdb-plx1fn42.cd.tencentcdb.com:10149/y3tu-cms??allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      primary: cms

mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml